### ISSUE TITLE
Reproduce the searched results for GDAS

### ISSUE THREAD

**Issue by UniSerj** [D-X-Y/AutoDL-Projects#45] opened 2020-01-02 07:51 UTC
Thanks for your awesome works!

The script for searching GDAS on a small search space (NAS-Bench-102) is given in README. If I want to reproduce the searched results in GDAS paper, is there a script available for searching on the full search space as well as the same network setting in the paper? I've noticed that the "search_space_name" in GDAS.sh can be changed to "full", however, the search code is based on NAS-Bench-102 settings. Or actually it doesn't matter and switching "search_space_name" to "full" is all I need?

Thank you.

**Comment by D-X-Y** [comment] 2020-01-02 08:44
@UniSerj Thanks for your interest. In the up-to-date version of this repo, the search_space_name in https://github.com/D-X-Y/NAS-Projects/blob/master/scripts-search/algos/GDAS.sh#L22 is set as `nas-bench-102`. This is used for our NAS-Bench-102 paper.

If you want to search over the original search space of GDAS, you need to change the macro structure in https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/cell_searchs/search_model_gdas.py and add the-DARTS-search-space in https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/cell_operations.py. You do not need to change the main search file (https://github.com/D-X-Y/NAS-Projects/blob/master/exps/algos/GDAS.py).

At the moment, I do not have enough time and machines to integrate the DARTS-search-space and test whether it can match the original performance in DARTS and GDAS. I will work on this once I have some free time. Sorry for the inconvenient.

Best regards,

**Comment by UniSerj** [comment] 2020-01-02 09:03
@D-X-Y Thanks a lot.

**Comment by D-X-Y** [comment] 2020-01-10 13:22
A quick update: the darts search space is added at https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/cell_operations.py#L30.
I will add the original supernet of GDAS soon.

**Comment by D-X-Y** [comment] 2020-01-11 14:43
@UniSerj I just uploaded the searching codes of GDAS on the NASNet search space (used in the original paper). Please use the following script:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/GDAS-search-NASNet-space.sh cifar10 1 -1
```
After each epoch, it will print the searched architecture at this line: `<<<--->>> The 001-250-th epoch :`

**Comment by Debrove** [comment] 2020-01-15 17:23
@D-X-Y Thanks for your quick update. During reproduce the results for DARTS, I am confused that the structure is `|skip_connect~0|+|skip_connect~0|skip_connect~1|+|skip_connect~0|skip_connect~1|skip_connect~2|` which repeatedly occured in the most epochs after changing the space name to darts. 

The question is that if I want to reproduce the searched structure like [genotype for DARTS](https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/nas_infer_model/DXYs/genotypes.py#L87), should I modify the code of [https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/models/cell_searchs/search_model_darts.py](https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/models/cell_searchs/search_model_darts.py) like [https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/models/cell_searchs/search_model_gdas_nasnet.py](https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/models/cell_searchs/search_model_gdas_nasnet.py).

Because I think the structure shown above is different from the structure from [genotype for DARTS](https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/nas_infer_model/DXYs/genotypes.py#L87) where each nodes have two operations, but in the structure shown above, there is one opreation in the first node, two operations in the second node and three in the third node. Do I misunderstand something? Please point out.

Thanks a lot.

**Comment by D-X-Y** [comment] 2020-01-17 11:11
hi @Debrove `|skip_connect~0|+|skip_connect~0|skip_connect~1|+|skip_connect~0|skip_connect~1|skip_connect~2|` is the DARTS result on the NAS-Bench-201 search space.

Yes, you should modify it as search_model_gdas_nasnet.py, but I just did it for you.
Now, you can use the following script to run the first-order DARTS with the DARTS(NASNet) search space.
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/DARTS1V-search-NASNet-space.sh cifar10 -1
```

Your understanding is correct. In this repo, I implemented multiple search spaces.

**Comment by Debrove** [comment] 2020-02-06 08:59
Hi @D-X-Y , I found something confused that the model_config is GDAS-NASNet-CIFAR.config in [DARTS1V-search-NASNet-space.sh#L38](https://github.com/D-X-Y/AutoDL-Projects/blob/master/scripts-search/DARTS1V-search-NASNet-space.sh#L38) and the name is GDAS in [DARTS-NASNet-CIFAR.config#L3](https://github.com/D-X-Y/AutoDL-Projects/blob/master/configs/search-archs/DARTS-NASNet-CIFAR.config#L3).

But when I change the model_config to DARTS, and meanwhile the name has changed to DARTS, it occurs a runtime error that the CUDA is out of memory. Is that something wrong？

Thank you.

**Comment by D-X-Y** [comment] 2020-02-06 23:16
@Debrove Sorry it is a typo in DARTS-NASNet-CIFAR.config, and I just fixed in the last commit. I modify the batchsize in DARTS.config, and you should be able to run now.

**Comment by Debrove** [comment] 2020-02-14 14:56
@D-X-Y Could you please update the SETN in NASNet search space if convenient. Thank you very much.

**Comment by D-X-Y** [comment] 2020-02-22 23:31
@Debrove thanks for your interest. I will work on this soon.

**Comment by D-X-Y** [comment] 2020-03-09 05:04
As all questions of GDAS have been answered, I will temporally close this issue.

**Closed by D-X-Y** 2020-03-09 05:04 UTC
Labels: enhancement
